Python 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.

= RESTART: C:\Users\Dell\Desktop\All\Doc\Mémoire\New\PredictionParArimaOptimise.py
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
solution optimale: 2,2,4 , fitness: 993.03786
CLIQUER SUR : Graphe de Prevision
+---------------------------------------+
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
patienter, ----warning pas genant-----
solution optimale: 1,2,1 , fitness: 993.03786
CLIQUER SUR : Graphe de Prevision
+---------------------------------------+
